// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Kyma Drone
A simple API to controll remote controlled drones


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    License: Apache 2.0
    Contact: Johannes Engelke

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
