// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// BackFlipDroneNoContentCode is the HTTP code returned for type BackFlipDroneNoContent
const BackFlipDroneNoContentCode int = 204

/*BackFlipDroneNoContent Drone performed a flip

swagger:response backFlipDroneNoContent
*/
type BackFlipDroneNoContent struct {
}

// NewBackFlipDroneNoContent creates BackFlipDroneNoContent with default headers values
func NewBackFlipDroneNoContent() *BackFlipDroneNoContent {

	return &BackFlipDroneNoContent{}
}

// WriteResponse to the client
func (o *BackFlipDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*BackFlipDroneDefault unexpected error

swagger:response backFlipDroneDefault
*/
type BackFlipDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewBackFlipDroneDefault creates BackFlipDroneDefault with default headers values
func NewBackFlipDroneDefault(code int) *BackFlipDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &BackFlipDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the back flip drone default response
func (o *BackFlipDroneDefault) WithStatusCode(code int) *BackFlipDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the back flip drone default response
func (o *BackFlipDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the back flip drone default response
func (o *BackFlipDroneDefault) WithPayload(payload *models.ErrorModel) *BackFlipDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the back flip drone default response
func (o *BackFlipDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BackFlipDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
