// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// BackwardDroneNoContentCode is the HTTP code returned for type BackwardDroneNoContent
const BackwardDroneNoContentCode int = 204

/*BackwardDroneNoContent Drone is turning backward

swagger:response backwardDroneNoContent
*/
type BackwardDroneNoContent struct {
}

// NewBackwardDroneNoContent creates BackwardDroneNoContent with default headers values
func NewBackwardDroneNoContent() *BackwardDroneNoContent {

	return &BackwardDroneNoContent{}
}

// WriteResponse to the client
func (o *BackwardDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*BackwardDroneDefault unexpected error

swagger:response backwardDroneDefault
*/
type BackwardDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewBackwardDroneDefault creates BackwardDroneDefault with default headers values
func NewBackwardDroneDefault(code int) *BackwardDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &BackwardDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the backward drone default response
func (o *BackwardDroneDefault) WithStatusCode(code int) *BackwardDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the backward drone default response
func (o *BackwardDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the backward drone default response
func (o *BackwardDroneDefault) WithPayload(payload *models.ErrorModel) *BackwardDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the backward drone default response
func (o *BackwardDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BackwardDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
