// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BackwardDroneHandlerFunc turns a function with the right signature into a backward drone handler
type BackwardDroneHandlerFunc func(BackwardDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BackwardDroneHandlerFunc) Handle(params BackwardDroneParams) middleware.Responder {
	return fn(params)
}

// BackwardDroneHandler interface for that can handle valid backward drone params
type BackwardDroneHandler interface {
	Handle(BackwardDroneParams) middleware.Responder
}

// NewBackwardDrone creates a new http.Handler for the backward drone operation
func NewBackwardDrone(ctx *middleware.Context, handler BackwardDroneHandler) *BackwardDrone {
	return &BackwardDrone{Context: ctx, Handler: handler}
}

/*BackwardDrone swagger:route POST /backward backwardDrone

Backward tells drone to go backward.

*/
type BackwardDrone struct {
	Context *middleware.Context
	Handler BackwardDroneHandler
}

func (o *BackwardDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBackwardDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
