// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ClawControlDroneHandlerFunc turns a function with the right signature into a claw control drone handler
type ClawControlDroneHandlerFunc func(ClawControlDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ClawControlDroneHandlerFunc) Handle(params ClawControlDroneParams) middleware.Responder {
	return fn(params)
}

// ClawControlDroneHandler interface for that can handle valid claw control drone params
type ClawControlDroneHandler interface {
	Handle(ClawControlDroneParams) middleware.Responder
}

// NewClawControlDrone creates a new http.Handler for the claw control drone operation
func NewClawControlDrone(ctx *middleware.Context, handler ClawControlDroneHandler) *ClawControlDrone {
	return &ClawControlDrone{Context: ctx, Handler: handler}
}

/*ClawControlDrone swagger:route POST /clawControl clawControlDrone

ClawControl tells drone to open or close the claw.

*/
type ClawControlDrone struct {
	Context *middleware.Context
	Handler ClawControlDroneHandler
}

func (o *ClawControlDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewClawControlDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
