// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// ClawControlDroneNoContentCode is the HTTP code returned for type ClawControlDroneNoContent
const ClawControlDroneNoContentCode int = 204

/*ClawControlDroneNoContent Drone is setting the lights

swagger:response clawControlDroneNoContent
*/
type ClawControlDroneNoContent struct {
}

// NewClawControlDroneNoContent creates ClawControlDroneNoContent with default headers values
func NewClawControlDroneNoContent() *ClawControlDroneNoContent {

	return &ClawControlDroneNoContent{}
}

// WriteResponse to the client
func (o *ClawControlDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*ClawControlDroneDefault unexpected error

swagger:response clawControlDroneDefault
*/
type ClawControlDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewClawControlDroneDefault creates ClawControlDroneDefault with default headers values
func NewClawControlDroneDefault(code int) *ClawControlDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &ClawControlDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the claw control drone default response
func (o *ClawControlDroneDefault) WithStatusCode(code int) *ClawControlDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the claw control drone default response
func (o *ClawControlDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the claw control drone default response
func (o *ClawControlDroneDefault) WithPayload(payload *models.ErrorModel) *ClawControlDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the claw control drone default response
func (o *ClawControlDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ClawControlDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
