// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ClockwiseDroneHandlerFunc turns a function with the right signature into a clockwise drone handler
type ClockwiseDroneHandlerFunc func(ClockwiseDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ClockwiseDroneHandlerFunc) Handle(params ClockwiseDroneParams) middleware.Responder {
	return fn(params)
}

// ClockwiseDroneHandler interface for that can handle valid clockwise drone params
type ClockwiseDroneHandler interface {
	Handle(ClockwiseDroneParams) middleware.Responder
}

// NewClockwiseDrone creates a new http.Handler for the clockwise drone operation
func NewClockwiseDrone(ctx *middleware.Context, handler ClockwiseDroneHandler) *ClockwiseDrone {
	return &ClockwiseDrone{Context: ctx, Handler: handler}
}

/*ClockwiseDrone swagger:route POST /clockwise clockwiseDrone

Clockwise tells drone to turn clockwise.

*/
type ClockwiseDrone struct {
	Context *middleware.Context
	Handler ClockwiseDroneHandler
}

func (o *ClockwiseDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewClockwiseDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
