// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// CounterClockwiseDroneNoContentCode is the HTTP code returned for type CounterClockwiseDroneNoContent
const CounterClockwiseDroneNoContentCode int = 204

/*CounterClockwiseDroneNoContent Drone is turning counter clockwise

swagger:response counterClockwiseDroneNoContent
*/
type CounterClockwiseDroneNoContent struct {
}

// NewCounterClockwiseDroneNoContent creates CounterClockwiseDroneNoContent with default headers values
func NewCounterClockwiseDroneNoContent() *CounterClockwiseDroneNoContent {

	return &CounterClockwiseDroneNoContent{}
}

// WriteResponse to the client
func (o *CounterClockwiseDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*CounterClockwiseDroneDefault unexpected error

swagger:response counterClockwiseDroneDefault
*/
type CounterClockwiseDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewCounterClockwiseDroneDefault creates CounterClockwiseDroneDefault with default headers values
func NewCounterClockwiseDroneDefault(code int) *CounterClockwiseDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &CounterClockwiseDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the counter clockwise drone default response
func (o *CounterClockwiseDroneDefault) WithStatusCode(code int) *CounterClockwiseDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the counter clockwise drone default response
func (o *CounterClockwiseDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the counter clockwise drone default response
func (o *CounterClockwiseDroneDefault) WithPayload(payload *models.ErrorModel) *CounterClockwiseDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the counter clockwise drone default response
func (o *CounterClockwiseDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CounterClockwiseDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
