// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// DownDroneNoContentCode is the HTTP code returned for type DownDroneNoContent
const DownDroneNoContentCode int = 204

/*DownDroneNoContent Drone is turning down

swagger:response downDroneNoContent
*/
type DownDroneNoContent struct {
}

// NewDownDroneNoContent creates DownDroneNoContent with default headers values
func NewDownDroneNoContent() *DownDroneNoContent {

	return &DownDroneNoContent{}
}

// WriteResponse to the client
func (o *DownDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DownDroneDefault unexpected error

swagger:response downDroneDefault
*/
type DownDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewDownDroneDefault creates DownDroneDefault with default headers values
func NewDownDroneDefault(code int) *DownDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &DownDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the down drone default response
func (o *DownDroneDefault) WithStatusCode(code int) *DownDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the down drone default response
func (o *DownDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the down drone default response
func (o *DownDroneDefault) WithPayload(payload *models.ErrorModel) *DownDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the down drone default response
func (o *DownDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
