// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// FlatTrimDroneNoContentCode is the HTTP code returned for type FlatTrimDroneNoContent
const FlatTrimDroneNoContentCode int = 204

/*FlatTrimDroneNoContent Drone is trimmed

swagger:response flatTrimDroneNoContent
*/
type FlatTrimDroneNoContent struct {
}

// NewFlatTrimDroneNoContent creates FlatTrimDroneNoContent with default headers values
func NewFlatTrimDroneNoContent() *FlatTrimDroneNoContent {

	return &FlatTrimDroneNoContent{}
}

// WriteResponse to the client
func (o *FlatTrimDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*FlatTrimDroneDefault unexpected error

swagger:response flatTrimDroneDefault
*/
type FlatTrimDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewFlatTrimDroneDefault creates FlatTrimDroneDefault with default headers values
func NewFlatTrimDroneDefault(code int) *FlatTrimDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &FlatTrimDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the flat trim drone default response
func (o *FlatTrimDroneDefault) WithStatusCode(code int) *FlatTrimDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the flat trim drone default response
func (o *FlatTrimDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the flat trim drone default response
func (o *FlatTrimDroneDefault) WithPayload(payload *models.ErrorModel) *FlatTrimDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the flat trim drone default response
func (o *FlatTrimDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FlatTrimDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
