// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// ForwardDroneNoContentCode is the HTTP code returned for type ForwardDroneNoContent
const ForwardDroneNoContentCode int = 204

/*ForwardDroneNoContent Drone is turning forward

swagger:response forwardDroneNoContent
*/
type ForwardDroneNoContent struct {
}

// NewForwardDroneNoContent creates ForwardDroneNoContent with default headers values
func NewForwardDroneNoContent() *ForwardDroneNoContent {

	return &ForwardDroneNoContent{}
}

// WriteResponse to the client
func (o *ForwardDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*ForwardDroneDefault unexpected error

swagger:response forwardDroneDefault
*/
type ForwardDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewForwardDroneDefault creates ForwardDroneDefault with default headers values
func NewForwardDroneDefault(code int) *ForwardDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &ForwardDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the forward drone default response
func (o *ForwardDroneDefault) WithStatusCode(code int) *ForwardDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the forward drone default response
func (o *ForwardDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the forward drone default response
func (o *ForwardDroneDefault) WithPayload(payload *models.ErrorModel) *ForwardDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the forward drone default response
func (o *ForwardDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ForwardDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
