// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ForwardDroneHandlerFunc turns a function with the right signature into a forward drone handler
type ForwardDroneHandlerFunc func(ForwardDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ForwardDroneHandlerFunc) Handle(params ForwardDroneParams) middleware.Responder {
	return fn(params)
}

// ForwardDroneHandler interface for that can handle valid forward drone params
type ForwardDroneHandler interface {
	Handle(ForwardDroneParams) middleware.Responder
}

// NewForwardDrone creates a new http.Handler for the forward drone operation
func NewForwardDrone(ctx *middleware.Context, handler ForwardDroneHandler) *ForwardDrone {
	return &ForwardDrone{Context: ctx, Handler: handler}
}

/*ForwardDrone swagger:route POST /forward forwardDrone

Forward tells drone to go forward.

*/
type ForwardDrone struct {
	Context *middleware.Context
	Handler ForwardDroneHandler
}

func (o *ForwardDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewForwardDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
