// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// FrontFlipDroneNoContentCode is the HTTP code returned for type FrontFlipDroneNoContent
const FrontFlipDroneNoContentCode int = 204

/*FrontFlipDroneNoContent Drone performed a flip

swagger:response frontFlipDroneNoContent
*/
type FrontFlipDroneNoContent struct {
}

// NewFrontFlipDroneNoContent creates FrontFlipDroneNoContent with default headers values
func NewFrontFlipDroneNoContent() *FrontFlipDroneNoContent {

	return &FrontFlipDroneNoContent{}
}

// WriteResponse to the client
func (o *FrontFlipDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*FrontFlipDroneDefault unexpected error

swagger:response frontFlipDroneDefault
*/
type FrontFlipDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewFrontFlipDroneDefault creates FrontFlipDroneDefault with default headers values
func NewFrontFlipDroneDefault(code int) *FrontFlipDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &FrontFlipDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the front flip drone default response
func (o *FrontFlipDroneDefault) WithStatusCode(code int) *FrontFlipDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the front flip drone default response
func (o *FrontFlipDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the front flip drone default response
func (o *FrontFlipDroneDefault) WithPayload(payload *models.ErrorModel) *FrontFlipDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the front flip drone default response
func (o *FrontFlipDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontFlipDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
