// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FrontFlipDroneHandlerFunc turns a function with the right signature into a front flip drone handler
type FrontFlipDroneHandlerFunc func(FrontFlipDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FrontFlipDroneHandlerFunc) Handle(params FrontFlipDroneParams) middleware.Responder {
	return fn(params)
}

// FrontFlipDroneHandler interface for that can handle valid front flip drone params
type FrontFlipDroneHandler interface {
	Handle(FrontFlipDroneParams) middleware.Responder
}

// NewFrontFlipDrone creates a new http.Handler for the front flip drone operation
func NewFrontFlipDrone(ctx *middleware.Context, handler FrontFlipDroneHandler) *FrontFlipDrone {
	return &FrontFlipDrone{Context: ctx, Handler: handler}
}

/*FrontFlipDrone swagger:route POST /frontFlip frontFlipDrone

FrontFlip tells the Minidrone to do a Front Flip

*/
type FrontFlipDrone struct {
	Context *middleware.Context
	Handler FrontFlipDroneHandler
}

func (o *FrontFlipDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFrontFlipDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
