// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// GunControlDroneNoContentCode is the HTTP code returned for type GunControlDroneNoContent
const GunControlDroneNoContentCode int = 204

/*GunControlDroneNoContent Drone shot the canno^

swagger:response gunControlDroneNoContent
*/
type GunControlDroneNoContent struct {
}

// NewGunControlDroneNoContent creates GunControlDroneNoContent with default headers values
func NewGunControlDroneNoContent() *GunControlDroneNoContent {

	return &GunControlDroneNoContent{}
}

// WriteResponse to the client
func (o *GunControlDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*GunControlDroneDefault unexpected error

swagger:response gunControlDroneDefault
*/
type GunControlDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGunControlDroneDefault creates GunControlDroneDefault with default headers values
func NewGunControlDroneDefault(code int) *GunControlDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &GunControlDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the gun control drone default response
func (o *GunControlDroneDefault) WithStatusCode(code int) *GunControlDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the gun control drone default response
func (o *GunControlDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the gun control drone default response
func (o *GunControlDroneDefault) WithPayload(payload *models.ErrorModel) *GunControlDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the gun control drone default response
func (o *GunControlDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GunControlDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
