// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// HaltDroneHandlerFunc turns a function with the right signature into a halt drone handler
type HaltDroneHandlerFunc func(HaltDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn HaltDroneHandlerFunc) Handle(params HaltDroneParams) middleware.Responder {
	return fn(params)
}

// HaltDroneHandler interface for that can handle valid halt drone params
type HaltDroneHandler interface {
	Handle(HaltDroneParams) middleware.Responder
}

// NewHaltDrone creates a new http.Handler for the halt drone operation
func NewHaltDrone(ctx *middleware.Context, handler HaltDroneHandler) *HaltDrone {
	return &HaltDrone{Context: ctx, Handler: handler}
}

/*HaltDrone swagger:route POST /halt haltDrone

Halt stops minidrone driver

*/
type HaltDrone struct {
	Context *middleware.Context
	Handler HaltDroneHandler
}

func (o *HaltDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewHaltDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
