// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// LandDroneHandlerFunc turns a function with the right signature into a land drone handler
type LandDroneHandlerFunc func(LandDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LandDroneHandlerFunc) Handle(params LandDroneParams) middleware.Responder {
	return fn(params)
}

// LandDroneHandler interface for that can handle valid land drone params
type LandDroneHandler interface {
	Handle(LandDroneParams) middleware.Responder
}

// NewLandDrone creates a new http.Handler for the land drone operation
func NewLandDrone(ctx *middleware.Context, handler LandDroneHandler) *LandDrone {
	return &LandDrone{Context: ctx, Handler: handler}
}

/*LandDrone swagger:route POST /land landDrone

Land tells the Minidrone to land

*/
type LandDrone struct {
	Context *middleware.Context
	Handler LandDroneHandler
}

func (o *LandDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLandDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
