// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// LeftFlipDroneNoContentCode is the HTTP code returned for type LeftFlipDroneNoContent
const LeftFlipDroneNoContentCode int = 204

/*LeftFlipDroneNoContent Drone performed a flip

swagger:response leftFlipDroneNoContent
*/
type LeftFlipDroneNoContent struct {
}

// NewLeftFlipDroneNoContent creates LeftFlipDroneNoContent with default headers values
func NewLeftFlipDroneNoContent() *LeftFlipDroneNoContent {

	return &LeftFlipDroneNoContent{}
}

// WriteResponse to the client
func (o *LeftFlipDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*LeftFlipDroneDefault unexpected error

swagger:response leftFlipDroneDefault
*/
type LeftFlipDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewLeftFlipDroneDefault creates LeftFlipDroneDefault with default headers values
func NewLeftFlipDroneDefault(code int) *LeftFlipDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &LeftFlipDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the left flip drone default response
func (o *LeftFlipDroneDefault) WithStatusCode(code int) *LeftFlipDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the left flip drone default response
func (o *LeftFlipDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the left flip drone default response
func (o *LeftFlipDroneDefault) WithPayload(payload *models.ErrorModel) *LeftFlipDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the left flip drone default response
func (o *LeftFlipDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LeftFlipDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
