// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// LeftDroneNoContentCode is the HTTP code returned for type LeftDroneNoContent
const LeftDroneNoContentCode int = 204

/*LeftDroneNoContent Drone is turning left

swagger:response leftDroneNoContent
*/
type LeftDroneNoContent struct {
}

// NewLeftDroneNoContent creates LeftDroneNoContent with default headers values
func NewLeftDroneNoContent() *LeftDroneNoContent {

	return &LeftDroneNoContent{}
}

// WriteResponse to the client
func (o *LeftDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*LeftDroneDefault unexpected error

swagger:response leftDroneDefault
*/
type LeftDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewLeftDroneDefault creates LeftDroneDefault with default headers values
func NewLeftDroneDefault(code int) *LeftDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &LeftDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the left drone default response
func (o *LeftDroneDefault) WithStatusCode(code int) *LeftDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the left drone default response
func (o *LeftDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the left drone default response
func (o *LeftDroneDefault) WithPayload(payload *models.ErrorModel) *LeftDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the left drone default response
func (o *LeftDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LeftDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
