// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// LeftFlipDroneHandlerFunc turns a function with the right signature into a left flip drone handler
type LeftFlipDroneHandlerFunc func(LeftFlipDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LeftFlipDroneHandlerFunc) Handle(params LeftFlipDroneParams) middleware.Responder {
	return fn(params)
}

// LeftFlipDroneHandler interface for that can handle valid left flip drone params
type LeftFlipDroneHandler interface {
	Handle(LeftFlipDroneParams) middleware.Responder
}

// NewLeftFlipDrone creates a new http.Handler for the left flip drone operation
func NewLeftFlipDrone(ctx *middleware.Context, handler LeftFlipDroneHandler) *LeftFlipDrone {
	return &LeftFlipDrone{Context: ctx, Handler: handler}
}

/*LeftFlipDrone swagger:route POST /leftFlip leftFlipDrone

LeftFlip tells the Minidrone to do a left Flip

*/
type LeftFlipDrone struct {
	Context *middleware.Context
	Handler LeftFlipDroneHandler
}

func (o *LeftFlipDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLeftFlipDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
