// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// LightControlDroneHandlerFunc turns a function with the right signature into a light control drone handler
type LightControlDroneHandlerFunc func(LightControlDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LightControlDroneHandlerFunc) Handle(params LightControlDroneParams) middleware.Responder {
	return fn(params)
}

// LightControlDroneHandler interface for that can handle valid light control drone params
type LightControlDroneHandler interface {
	Handle(LightControlDroneParams) middleware.Responder
}

// NewLightControlDrone creates a new http.Handler for the light control drone operation
func NewLightControlDrone(ctx *middleware.Context, handler LightControlDroneHandler) *LightControlDrone {
	return &LightControlDrone{Context: ctx, Handler: handler}
}

/*LightControlDrone swagger:route POST /lightControl lightControlDrone

LightControl tells drone to set the light mode.

*/
type LightControlDrone struct {
	Context *middleware.Context
	Handler LightControlDroneHandler
}

func (o *LightControlDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLightControlDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
