// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// RightFlipDroneNoContentCode is the HTTP code returned for type RightFlipDroneNoContent
const RightFlipDroneNoContentCode int = 204

/*RightFlipDroneNoContent Drone performed a flip

swagger:response rightFlipDroneNoContent
*/
type RightFlipDroneNoContent struct {
}

// NewRightFlipDroneNoContent creates RightFlipDroneNoContent with default headers values
func NewRightFlipDroneNoContent() *RightFlipDroneNoContent {

	return &RightFlipDroneNoContent{}
}

// WriteResponse to the client
func (o *RightFlipDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*RightFlipDroneDefault unexpected error

swagger:response rightFlipDroneDefault
*/
type RightFlipDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewRightFlipDroneDefault creates RightFlipDroneDefault with default headers values
func NewRightFlipDroneDefault(code int) *RightFlipDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &RightFlipDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the right flip drone default response
func (o *RightFlipDroneDefault) WithStatusCode(code int) *RightFlipDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the right flip drone default response
func (o *RightFlipDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the right flip drone default response
func (o *RightFlipDroneDefault) WithPayload(payload *models.ErrorModel) *RightFlipDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the right flip drone default response
func (o *RightFlipDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RightFlipDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
