// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// ShipPackageNoContentCode is the HTTP code returned for type ShipPackageNoContent
const ShipPackageNoContentCode int = 204

/*ShipPackageNoContent Drone is setting the lights

swagger:response shipPackageNoContent
*/
type ShipPackageNoContent struct {
}

// NewShipPackageNoContent creates ShipPackageNoContent with default headers values
func NewShipPackageNoContent() *ShipPackageNoContent {

	return &ShipPackageNoContent{}
}

// WriteResponse to the client
func (o *ShipPackageNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*ShipPackageDefault unexpected error

swagger:response shipPackageDefault
*/
type ShipPackageDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewShipPackageDefault creates ShipPackageDefault with default headers values
func NewShipPackageDefault(code int) *ShipPackageDefault {
	if code <= 0 {
		code = 500
	}

	return &ShipPackageDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the ship package default response
func (o *ShipPackageDefault) WithStatusCode(code int) *ShipPackageDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the ship package default response
func (o *ShipPackageDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the ship package default response
func (o *ShipPackageDefault) WithPayload(payload *models.ErrorModel) *ShipPackageDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ship package default response
func (o *ShipPackageDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShipPackageDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
