// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ShipPackageHandlerFunc turns a function with the right signature into a ship package handler
type ShipPackageHandlerFunc func(ShipPackageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShipPackageHandlerFunc) Handle(params ShipPackageParams) middleware.Responder {
	return fn(params)
}

// ShipPackageHandler interface for that can handle valid ship package params
type ShipPackageHandler interface {
	Handle(ShipPackageParams) middleware.Responder
}

// NewShipPackage creates a new http.Handler for the ship package operation
func NewShipPackage(ctx *middleware.Context, handler ShipPackageHandler) *ShipPackage {
	return &ShipPackage{Context: ctx, Handler: handler}
}

/*ShipPackage swagger:route POST /shipPackage shipPackage

shipPackage tells drone to ship a package.

*/
type ShipPackage struct {
	Context *middleware.Context
	Handler ShipPackageHandler
}

func (o *ShipPackage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShipPackageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
