// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// StartDroneNoContentCode is the HTTP code returned for type StartDroneNoContent
const StartDroneNoContentCode int = 204

/*StartDroneNoContent Drone started

swagger:response startDroneNoContent
*/
type StartDroneNoContent struct {
}

// NewStartDroneNoContent creates StartDroneNoContent with default headers values
func NewStartDroneNoContent() *StartDroneNoContent {

	return &StartDroneNoContent{}
}

// WriteResponse to the client
func (o *StartDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*StartDroneDefault unexpected error

swagger:response startDroneDefault
*/
type StartDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewStartDroneDefault creates StartDroneDefault with default headers values
func NewStartDroneDefault(code int) *StartDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &StartDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the start drone default response
func (o *StartDroneDefault) WithStatusCode(code int) *StartDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the start drone default response
func (o *StartDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the start drone default response
func (o *StartDroneDefault) WithPayload(payload *models.ErrorModel) *StartDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start drone default response
func (o *StartDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
