// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// StopDroneNoContentCode is the HTTP code returned for type StopDroneNoContent
const StopDroneNoContentCode int = 204

/*StopDroneNoContent Drone stoped

swagger:response stopDroneNoContent
*/
type StopDroneNoContent struct {
}

// NewStopDroneNoContent creates StopDroneNoContent with default headers values
func NewStopDroneNoContent() *StopDroneNoContent {

	return &StopDroneNoContent{}
}

// WriteResponse to the client
func (o *StopDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*StopDroneDefault unexpected error

swagger:response stopDroneDefault
*/
type StopDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewStopDroneDefault creates StopDroneDefault with default headers values
func NewStopDroneDefault(code int) *StopDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &StopDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the stop drone default response
func (o *StopDroneDefault) WithStatusCode(code int) *StopDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the stop drone default response
func (o *StopDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the stop drone default response
func (o *StopDroneDefault) WithPayload(payload *models.ErrorModel) *StopDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stop drone default response
func (o *StopDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StopDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
