// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// TakePictureDroneNoContentCode is the HTTP code returned for type TakePictureDroneNoContent
const TakePictureDroneNoContentCode int = 204

/*TakePictureDroneNoContent Picture taken

swagger:response takePictureDroneNoContent
*/
type TakePictureDroneNoContent struct {
}

// NewTakePictureDroneNoContent creates TakePictureDroneNoContent with default headers values
func NewTakePictureDroneNoContent() *TakePictureDroneNoContent {

	return &TakePictureDroneNoContent{}
}

// WriteResponse to the client
func (o *TakePictureDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*TakePictureDroneDefault unexpected error

swagger:response takePictureDroneDefault
*/
type TakePictureDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewTakePictureDroneDefault creates TakePictureDroneDefault with default headers values
func NewTakePictureDroneDefault(code int) *TakePictureDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &TakePictureDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the take picture drone default response
func (o *TakePictureDroneDefault) WithStatusCode(code int) *TakePictureDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the take picture drone default response
func (o *TakePictureDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the take picture drone default response
func (o *TakePictureDroneDefault) WithPayload(payload *models.ErrorModel) *TakePictureDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the take picture drone default response
func (o *TakePictureDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TakePictureDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
