// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/joek/kyma-drone/pkg/models"
)

// TakeOffDroneNoContentCode is the HTTP code returned for type TakeOffDroneNoContent
const TakeOffDroneNoContentCode int = 204

/*TakeOffDroneNoContent Drone took off

swagger:response takeOffDroneNoContent
*/
type TakeOffDroneNoContent struct {
}

// NewTakeOffDroneNoContent creates TakeOffDroneNoContent with default headers values
func NewTakeOffDroneNoContent() *TakeOffDroneNoContent {

	return &TakeOffDroneNoContent{}
}

// WriteResponse to the client
func (o *TakeOffDroneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*TakeOffDroneDefault unexpected error

swagger:response takeOffDroneDefault
*/
type TakeOffDroneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewTakeOffDroneDefault creates TakeOffDroneDefault with default headers values
func NewTakeOffDroneDefault(code int) *TakeOffDroneDefault {
	if code <= 0 {
		code = 500
	}

	return &TakeOffDroneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the take off drone default response
func (o *TakeOffDroneDefault) WithStatusCode(code int) *TakeOffDroneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the take off drone default response
func (o *TakeOffDroneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the take off drone default response
func (o *TakeOffDroneDefault) WithPayload(payload *models.ErrorModel) *TakeOffDroneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the take off drone default response
func (o *TakeOffDroneDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TakeOffDroneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
