// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpDroneHandlerFunc turns a function with the right signature into a up drone handler
type UpDroneHandlerFunc func(UpDroneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpDroneHandlerFunc) Handle(params UpDroneParams) middleware.Responder {
	return fn(params)
}

// UpDroneHandler interface for that can handle valid up drone params
type UpDroneHandler interface {
	Handle(UpDroneParams) middleware.Responder
}

// NewUpDrone creates a new http.Handler for the up drone operation
func NewUpDrone(ctx *middleware.Context, handler UpDroneHandler) *UpDrone {
	return &UpDrone{Context: ctx, Handler: handler}
}

/*UpDrone swagger:route POST /up upDrone

Up tells drone to go up.

*/
type UpDrone struct {
	Context *middleware.Context
	Handler UpDroneHandler
}

func (o *UpDrone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpDroneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
