// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ShippingModel shipping model
// swagger:model ShippingModel
type ShippingModel struct {

	// order code
	// Required: true
	OrderCode *string `json:"OrderCode"`
}

// Validate validates this shipping model
func (m *ShippingModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShippingModel) validateOrderCode(formats strfmt.Registry) error {

	if err := validate.Required("OrderCode", "body", m.OrderCode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ShippingModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShippingModel) UnmarshalBinary(b []byte) error {
	var res ShippingModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
