// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ValueModel value model
// swagger:model ValueModel
type ValueModel struct {

	// value
	// Required: true
	// Maximum: 100
	// Minimum: 0
	Value *int32 `json:"value"`
}

// Validate validates this value model
func (m *ValueModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValueModel) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	if err := validate.MinimumInt("value", "body", int64(*m.Value), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("value", "body", int64(*m.Value), 100, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ValueModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValueModel) UnmarshalBinary(b []byte) error {
	var res ValueModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
